//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketBall.Data.basketball
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id { get; set; }
        public Nullable<int> homeTeamId { get; set; }
        public Nullable<int> awayTeamId { get; set; }
        public Nullable<int> quarter1Home { get; set; }
        public Nullable<int> quarter1Away { get; set; }
        public Nullable<int> quarter2Home { get; set; }
        public Nullable<int> quarter2Away { get; set; }
        public Nullable<int> quarter3Home { get; set; }
        public Nullable<int> quarter3Away { get; set; }
        public Nullable<int> quarter4Home { get; set; }
        public Nullable<int> quarter4Away { get; set; }
        public string description { get; set; }
    }
}
