//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketBall.Data.basketball
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basketballEntities : DbContext
    {
        public basketballEntities()
            : base("name=basketballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<winLossRecord> winLossRecords { get; set; }
    }
}
